#!/usr/bin/env bash

sudo apt-get -y install vim python3 tmux git build-essential cmake vim-nox python3-dev mono-complete golang nodejs default-jdk npm
# to read more about the proceeding line check out:
# https://www.google.com/search?channel=fs&client=ubuntu&q=when+is+readarray+supported+in+bash
readarray -d '' files < <(find . -max-depth 1 -name "*" -print0)
for each in "${files[@]}";
do
	if [ $each == "config"]
	then
		continue
	elif [ -f $each ]
	then
		ln $each ~/$each
	elif [ -d $each ];
	then
		ln -s $each ~/$each
	else
		echo "$each is not a file of a directory" 2>&
		exit 1
	fi
	
done

if [ -d .vim/pack/plugins/start ];
then
	cd .vim/pack/plugins/start
	git clone https://github.com/vim-scripts/PaperColor.vim.git
	git clone https://github.com/Raimondi/delimitMate.git
	git clone https://github.com/vim-airline/vim-airline.git
	git clone https://github.com/vim-airline/vim-airline-themes.git
	git clone https://github.com/christoomey/vim-conflicted.git
	git clone https://github.com/tpope/vim-fugitive.git
	git clone https://github.com/artur-shaik/vim-javacomplete2.git
	git clone https://github.com/jez/vim-superman.git
	git clone https://github.com/ycm-core/YouCompleteMe.git
	if [ -d YouCompleteMe ];
	then
		cd YouCompleteMe
		python3 install.py --all
	fi
fi

