#!/usr/bin/env bash

function PROMPT_AND_READ {
	if [ -e "$HOME/$each" ]
	then
		local answer='a'
		while [  ${answer,} != 'y' ] && [ ${answer,} != 'n' ] 
		do echo "would you like to replace $each in ${HOME}? (Y/n)"
			read answer
		done
		if [ ${answer} == 'y' ]
		then
			rm -fr "$HOME/$each"
		fi
	fi
}
declare -u do_instal
while [ "${do_instal}" != "Y" ] && [ "${do_instal}" != "N" ]
do
	read -p "Do you want to install a bunch of programs (Y/n)? " do_instal
done


if [ ${do_instal} = "Y" ]; then
	# break long linst of arguments to apt-get install for slow computers.
	sudo apt-get -y install vim python3 tmux git 
	sudo apt-get -y install build-essential cmake vim-nox python3-dev 
	sudo apt-get -y install mono-complete golang nodejs default-jdk npm
	sudo apt-get -y install g++ gcc clang
	sudo apt-get -y install lm-sensors
	sudo apt-get -y install ncbi-blast+
	sudo apt-get -y install vim-gtk3 sl
	sudo apt-get -y install gdb valgrind 
	sudo apt-get -y install python3.10 # might be out of date by the time you use this
	sudo apt-get -y install python3-ipython
	sudo apt-get -y install rustc cargo
	sudo apt-get -y install libgl1-mesa-glx libegl1-mesa libxrandr2 libxrandr2 libxss1 libxcursor1 libxcomposite1 libasound2 libxi6 libxtst6 # needed for graphical stuff with anaconda
	sudo apt-get -y install moreutils
	sudo apt-get -y install igv

fi
# to read more about the proceeding line check out:
# https://www.google.com/search?channel=fs&client=ubuntu&q=when+is+readarray+supported+in+bash
readarray -d '' files < <(find . -maxdepth 1 -name "*" -print0)
for each in "${files[@]}";
do

	each=${each#./}
	if [[ ! $each =~ ^\.[^.].* ]] || [ "$each" == ".git" ] # only dot,no git
	then
		continue
	elif [ -f $each ] # files can be hard linked
	then
		PROMPT_AND_READ
		ln -v "$each" "$HOME/$each"
	elif [ -d $each ]; # directories need symlink
	then
		PROMPT_AND_READ
		ln -s -v "repos/dot_files/$each" "$HOME/$each" 
	fi
done

if [ -d .vim/pack/plugins/start ];
then
	cd .vim/pack/plugins/start
	git clone https://github.com/Raimondi/delimitMate.git
	git clone https://github.com/NLKNguyen/papercolor-theme.git
	git clone https://github.com/christoomey/vim-conflicted.git
	git clone https://github.com/vim-airline/vim-airline.git
	git clone https://github.com/vim-airline/vim-airline-themes.git
	git clone https://github.com/tpope/vim-fugitive.git
	git clone https://github.com/artur-shaik/vim-javacomplete2.git
	git clone https://github.com/jez/vim-superman.git
	echo "YouCompleteMe is over a Gig, do you still want it?"
	read -r answer
	if [ ${answer,} == 'y' ]
	then
		git clone https://github.com/ycm-core/YouCompleteMe.git
		if [ -d YouCompleteMe ];
		then
			cd YouCompleteMe
			git submodule update --init --recursive
			python3 install.py --all
		fi
	fi
fi

