#!/usr/bin/env bash

sudo apt-get -y install vim python3 tmux git build-essential cmake vim-nox python3-dev mono-complete golang nodejs default-jdk npm
files=(*)
for each in "${files[@]}";
do
	if [ -f $each ]
	then
		ln $each ~/$each
	elif [ -d $each ];
	then
		ln -s $each ~/$each
	else
		echo "$each is not a files of a directory" 2>&
		exit 1
	fi
	
done

if [ -d .vim/pack/plugins/start ];
then
	cd .vim/pack/plugins/start
	git clone https://github.com/vim-scripts/PaperColor.vim.git
	git clone https://github.com/Raimondi/delimitMate.git
	git clone https://github.com/vim-airline/vim-airline.git
	git clone https://github.com/vim-airline/vim-airline-themes.git
	git clone https://github.com/christoomey/vim-conflicted.git
	git clone https://github.com/tpope/vim-fugitive.git
	git clone https://github.com/artur-shaik/vim-javacomplete2.git
	git clone https://github.com/jez/vim-superman.git
	git clone https://github.com/ycm-core/YouCompleteMe.git
	if [ -d YouCompleteMe ];
	then
		cd YouCompleteMe
		python3 install.py --all
	fi
fi

